name: Build macOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build app
        run: |
          pyinstaller --windowed main.py

      - name: Upload app
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App
          path: dist/
